### ISSUE TITLE
SQLite3 import library

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet-scripts#26]
MSVC needs an import library `sqlite3.lib` to link to the `sqlite3.dll`. It can be generated from the .def file as follows (dll doesn't need to be present even though it's specified on the command line):
```
x86_64-w64-mingw32-dlltool -d sqlite3.def -D sqlite3.dll -m i386:x86-64 -l sqlite3.lib
```

@def- Could you integrate that into the script and re-run it?

It seems we already do similar stuff for the other libraries... :)

**Comment by def-** [comment]
Oops, will add soon

**Comment by def-** [comment]
Should we also rename the dll to sqlite3.dll? Where to get the sqlite3.def file?
