### ISSUE TITLE
Escape Discord usernames for records channel

### ISSUE THREAD

**Issue by Scrumplex** [ddnet/ddnet-scripts#28]
As posted in ddnet/ddnet-discordbot#15 the webhook responsible for the #records channel on Discord does not escape sequences like `@everyone`. I would suggest to also escape the `@` symbol.

For source of the bug see [line 31 in file servers/scripts/discord-ranks.py](https://github.com/ddnet/ddnet-scripts/blob/5dd15b75f92e7a71912880be5e2c0769f5918b9a/servers/scripts/discord-ranks.py#L31)

**Comment by Scrumplex** [comment]
Additionally see Line 84 in file servers/scripts/discord-ranks.py

https://github.com/ddnet/ddnet-scripts/blob/5dd15b75f92e7a71912880be5e2c0769f5918b9a/servers/scripts/discord-ranks.py#L84

**Comment by Banana090** [comment]
There is an extra field in discord API that you can send with message or right after websocket handshake to ask discord disable any mentions in bot's message(s)

**Comment by def-** [comment]
Fixed with the allowed_mentions field: https://discord.com/developers/docs/resources/channel#allowed-mentions-object

Thanks @Banana090
