### ISSUE TITLE
Also provide checksum for source tarball

### ISSUE THREAD

**Issue by rffontenelle** [ddnet/ddnet-scripts#3]
(Not sure whether this is the correct repository, but here we go..)
Currently, [DDNet's Downloads page](https://ddnet.tw/downloads/) provides one file for [MD5](https://ddnet.tw/downloads/md5sums) and another for [SHA256](https://ddnet.tw/downloads/sha256sums), which don't include the released source tarball (ex.: "ddnet-10.6.7.tar.gz").

Please include checksums for released source tarball, to ease integrity double-checking by package maintainer.

**Comment by def-** [comment]
Source tarball is provided by github and can change since github could just repack the zip/tar.gz in a different order. Why do you need this? The commit ID from git might be the closes to that right now.

**Comment by rffontenelle** [comment]
Right now I wanted to double-check the md5sum for "ddnet-10.6.7.tar.gz" which changed from e047fe1af084c1a2f627c8a162cbb867 to 2fc4e7a471adbb5aecb3c8ac488884d2 without any version bump, and I wanted to know whether it was an error on my end or the tarball really got updated. Not really a big deal, actually.

**Comment by def-** [comment]
github probably recreated it because I temporarily moved the repo away and back again. Sorry! Maybe we should provide the source code downloads on ddnet.tw? Any opinions?

**Comment by def-** [comment]
Future versions of ddnet will have the source code hosted on ddnet.tw

**Comment by rffontenelle** [comment]
Sorry for the delay. Looks good to me. Thanks!
